# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6dba2f8b80532a78388e6844528360bd63fbad358f9adf03147f95036eb89ae574923a60bee9dde9f48e0fd6cbe85a180aa0989bc9a42c1f3405e5e16a78e4

test:
  secret_key_base: d4e30cc5d3d00651bd93555062a77864121ca121c34c8bcb8accb6a6b5e577a0ee007374f3eb06fa0ee10ff04a0ef457857d4d79d4b2685af24abf07ae6391ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
